/*
 * DolphinSchedulerApiDocsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m6712345.m30.m168.m172.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * ExecutionTypeEnum to be used.
 */
public enum ExecutionTypeEnum {
    PARALLEL,

    SERIAL_WAIT,

    SERIAL_DISCARD,

    SERIAL_PRIORITY;


    private static TreeMap<String, ExecutionTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        PARALLEL.value = "PARALLEL";
        SERIAL_WAIT.value = "SERIAL_WAIT";
        SERIAL_DISCARD.value = "SERIAL_DISCARD";
        SERIAL_PRIORITY.value = "SERIAL_PRIORITY";

        valueMap.put("PARALLEL", PARALLEL);
        valueMap.put("SERIAL_WAIT", SERIAL_WAIT);
        valueMap.put("SERIAL_DISCARD", SERIAL_DISCARD);
        valueMap.put("SERIAL_PRIORITY", SERIAL_PRIORITY);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ExecutionTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ExecutionTypeEnum values to list of string values.
     * @param toConvert The list of ExecutionTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ExecutionTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ExecutionTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 