/*
 * DolphinSchedulerApiDocsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m6712345.m30.m168.m172.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * OperationTypeEnum to be used.
 */
public enum OperationTypeEnum {
    CREATE,

    READ,

    UPDATE,

    DELETE;


    private static TreeMap<String, OperationTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        CREATE.value = "CREATE";
        READ.value = "READ";
        UPDATE.value = "UPDATE";
        DELETE.value = "DELETE";

        valueMap.put("CREATE", CREATE);
        valueMap.put("READ", READ);
        valueMap.put("UPDATE", UPDATE);
        valueMap.put("DELETE", DELETE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static OperationTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of OperationTypeEnum values to list of string values.
     * @param toConvert The list of OperationTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<OperationTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (OperationTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 