/*
 * DolphinSchedulerApiDocsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m6712345.m30.m168.m172.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * ReleaseStateEnum to be used.
 */
public enum ReleaseStateEnum {
    OFFLINE,

    ONLINE;


    private static TreeMap<String, ReleaseStateEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        OFFLINE.value = "OFFLINE";
        ONLINE.value = "ONLINE";

        valueMap.put("OFFLINE", OFFLINE);
        valueMap.put("ONLINE", ONLINE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ReleaseStateEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ReleaseStateEnum values to list of string values.
     * @param toConvert The list of ReleaseStateEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ReleaseStateEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ReleaseStateEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 