/*
 * DolphinSchedulerApiDocsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m6712345.m30.m168.m172.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ResponseEntity type.
 */
public class ResponseEntity {
    private Object body;
    private StatusCodeEnum statusCode;
    private Integer statusCodeValue;

    /**
     * Default constructor.
     */
    public ResponseEntity() {
    }

    /**
     * Initialization constructor.
     * @param  body  Object value for body.
     * @param  statusCode  StatusCodeEnum value for statusCode.
     * @param  statusCodeValue  Integer value for statusCodeValue.
     */
    public ResponseEntity(
            Object body,
            StatusCodeEnum statusCode,
            Integer statusCodeValue) {
        this.body = body;
        this.statusCode = statusCode;
        this.statusCodeValue = statusCodeValue;
    }

    /**
     * Getter for Body.
     * @return Returns the Object
     */
    @JsonGetter("body")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getBody() {
        return body;
    }

    /**
     * Setter for Body.
     * @param body Value for Object
     */
    @JsonSetter("body")
    public void setBody(Object body) {
        this.body = body;
    }

    /**
     * Getter for StatusCode.
     * @return Returns the StatusCodeEnum
     */
    @JsonGetter("statusCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public StatusCodeEnum getStatusCode() {
        return statusCode;
    }

    /**
     * Setter for StatusCode.
     * @param statusCode Value for StatusCodeEnum
     */
    @JsonSetter("statusCode")
    public void setStatusCode(StatusCodeEnum statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * Getter for StatusCodeValue.
     * @return Returns the Integer
     */
    @JsonGetter("statusCodeValue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getStatusCodeValue() {
        return statusCodeValue;
    }

    /**
     * Setter for StatusCodeValue.
     * @param statusCodeValue Value for Integer
     */
    @JsonSetter("statusCodeValue")
    public void setStatusCodeValue(Integer statusCodeValue) {
        this.statusCodeValue = statusCodeValue;
    }

    /**
     * Converts this ResponseEntity into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseEntity [" + "body=" + body + ", statusCode=" + statusCode
                + ", statusCodeValue=" + statusCodeValue + "]";
    }

    /**
     * Builds a new {@link ResponseEntity.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseEntity.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .body(getBody())
                .statusCode(getStatusCode())
                .statusCodeValue(getStatusCodeValue());
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseEntity}.
     */
    public static class Builder {
        private Object body;
        private StatusCodeEnum statusCode;
        private Integer statusCodeValue;



        /**
         * Setter for body.
         * @param  body  Object value for body.
         * @return Builder
         */
        public Builder body(Object body) {
            this.body = body;
            return this;
        }

        /**
         * Setter for statusCode.
         * @param  statusCode  StatusCodeEnum value for statusCode.
         * @return Builder
         */
        public Builder statusCode(StatusCodeEnum statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Setter for statusCodeValue.
         * @param  statusCodeValue  Integer value for statusCodeValue.
         * @return Builder
         */
        public Builder statusCodeValue(Integer statusCodeValue) {
            this.statusCodeValue = statusCodeValue;
            return this;
        }

        /**
         * Builds a new {@link ResponseEntity} object using the set fields.
         * @return {@link ResponseEntity}
         */
        public ResponseEntity build() {
            return new ResponseEntity(body, statusCode, statusCodeValue);
        }
    }
}
