/*
 * DolphinSchedulerApiDocsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m6712345.m30.m168.m172.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ResultProcessInstance type.
 */
public class ResultProcessInstance {
    private Integer code;
    private ProcessInstance data;
    private Boolean failed;
    private String msg;
    private Boolean success;

    /**
     * Default constructor.
     */
    public ResultProcessInstance() {
    }

    /**
     * Initialization constructor.
     * @param  code  Integer value for code.
     * @param  data  ProcessInstance value for data.
     * @param  failed  Boolean value for failed.
     * @param  msg  String value for msg.
     * @param  success  Boolean value for success.
     */
    public ResultProcessInstance(
            Integer code,
            ProcessInstance data,
            Boolean failed,
            String msg,
            Boolean success) {
        this.code = code;
        this.data = data;
        this.failed = failed;
        this.msg = msg;
        this.success = success;
    }

    /**
     * Getter for Code.
     * @return Returns the Integer
     */
    @JsonGetter("code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * @param code Value for Integer
     */
    @JsonSetter("code")
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * Getter for Data.
     * @return Returns the ProcessInstance
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProcessInstance getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for ProcessInstance
     */
    @JsonSetter("data")
    public void setData(ProcessInstance data) {
        this.data = data;
    }

    /**
     * Getter for Failed.
     * @return Returns the Boolean
     */
    @JsonGetter("failed")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getFailed() {
        return failed;
    }

    /**
     * Setter for Failed.
     * @param failed Value for Boolean
     */
    @JsonSetter("failed")
    public void setFailed(Boolean failed) {
        this.failed = failed;
    }

    /**
     * Getter for Msg.
     * @return Returns the String
     */
    @JsonGetter("msg")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMsg() {
        return msg;
    }

    /**
     * Setter for Msg.
     * @param msg Value for String
     */
    @JsonSetter("msg")
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * Getter for Success.
     * @return Returns the Boolean
     */
    @JsonGetter("success")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getSuccess() {
        return success;
    }

    /**
     * Setter for Success.
     * @param success Value for Boolean
     */
    @JsonSetter("success")
    public void setSuccess(Boolean success) {
        this.success = success;
    }

    /**
     * Converts this ResultProcessInstance into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResultProcessInstance [" + "code=" + code + ", data=" + data + ", failed=" + failed
                + ", msg=" + msg + ", success=" + success + "]";
    }

    /**
     * Builds a new {@link ResultProcessInstance.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResultProcessInstance.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .code(getCode())
                .data(getData())
                .failed(getFailed())
                .msg(getMsg())
                .success(getSuccess());
        return builder;
    }

    /**
     * Class to build instances of {@link ResultProcessInstance}.
     */
    public static class Builder {
        private Integer code;
        private ProcessInstance data;
        private Boolean failed;
        private String msg;
        private Boolean success;



        /**
         * Setter for code.
         * @param  code  Integer value for code.
         * @return Builder
         */
        public Builder code(Integer code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  ProcessInstance value for data.
         * @return Builder
         */
        public Builder data(ProcessInstance data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for failed.
         * @param  failed  Boolean value for failed.
         * @return Builder
         */
        public Builder failed(Boolean failed) {
            this.failed = failed;
            return this;
        }

        /**
         * Setter for msg.
         * @param  msg  String value for msg.
         * @return Builder
         */
        public Builder msg(String msg) {
            this.msg = msg;
            return this;
        }

        /**
         * Setter for success.
         * @param  success  Boolean value for success.
         * @return Builder
         */
        public Builder success(Boolean success) {
            this.success = success;
            return this;
        }

        /**
         * Builds a new {@link ResultProcessInstance} object using the set fields.
         * @return {@link ResultProcessInstance}
         */
        public ResultProcessInstance build() {
            return new ResultProcessInstance(code, data, failed, msg, success);
        }
    }
}
