/*
 * DolphinSchedulerApiDocsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m6712345.m30.m168.m172.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * TaskDependTypeEnum to be used.
 */
public enum TaskDependTypeEnum {
    TASK_ONLY,

    TASK_PRE,

    TASK_POST;


    private static TreeMap<String, TaskDependTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        TASK_ONLY.value = "TASK_ONLY";
        TASK_PRE.value = "TASK_PRE";
        TASK_POST.value = "TASK_POST";

        valueMap.put("TASK_ONLY", TASK_ONLY);
        valueMap.put("TASK_PRE", TASK_PRE);
        valueMap.put("TASK_POST", TASK_POST);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static TaskDependTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TaskDependTypeEnum values to list of string values.
     * @param toConvert The list of TaskDependTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TaskDependTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TaskDependTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 