/*
 * DolphinSchedulerApiDocsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m6712345.m30.m168.m172.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * TimeoutNotifyStrategyEnum to be used.
 */
public enum TimeoutNotifyStrategyEnum {
    WARN,

    FAILED,

    WARNFAILED;


    private static TreeMap<String, TimeoutNotifyStrategyEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        WARN.value = "WARN";
        FAILED.value = "FAILED";
        WARNFAILED.value = "WARNFAILED";

        valueMap.put("WARN", WARN);
        valueMap.put("FAILED", FAILED);
        valueMap.put("WARNFAILED", WARNFAILED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static TimeoutNotifyStrategyEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TimeoutNotifyStrategyEnum values to list of string values.
     * @param toConvert The list of TimeoutNotifyStrategyEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TimeoutNotifyStrategyEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TimeoutNotifyStrategyEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 