/*
 * DolphinSchedulerApiDocsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m6712345.m30.m168.m172.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * UserTypeEnum to be used.
 */
public enum UserTypeEnum {
    ADMIN_USER,

    GENERAL_USER;


    private static TreeMap<String, UserTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ADMIN_USER.value = "ADMIN_USER";
        GENERAL_USER.value = "GENERAL_USER";

        valueMap.put("ADMIN_USER", ADMIN_USER);
        valueMap.put("GENERAL_USER", GENERAL_USER);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static UserTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of UserTypeEnum values to list of string values.
     * @param toConvert The list of UserTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<UserTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (UserTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 