/*
 * DolphinSchedulerApiDocsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package m6712345.m30.m168.m172.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * WarningTypeEnum to be used.
 */
public enum WarningTypeEnum {
    NONE,

    SUCCESS,

    FAILURE,

    ALL;


    private static TreeMap<String, WarningTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        NONE.value = "NONE";
        SUCCESS.value = "SUCCESS";
        FAILURE.value = "FAILURE";
        ALL.value = "ALL";

        valueMap.put("NONE", NONE);
        valueMap.put("SUCCESS", SUCCESS);
        valueMap.put("FAILURE", FAILURE);
        valueMap.put("ALL", ALL);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static WarningTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of WarningTypeEnum values to list of string values.
     * @param toConvert The list of WarningTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<WarningTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (WarningTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 